import { VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '0.23.1-rc.0:1',
  releaseNotes: {
    en_US: `Advances the bundled vLLM nightly build to commit 6607a80 (still on the upstream 0.23.1rc0 line). Highlights: new model support for MiniMax M3 and a Qwen3-VL video loader, a security fix enforcing the audio upload size limit before the full file is materialized, multimodal token counts now reported in usage.prompt_tokens_details, and bug fixes for out-of-range temperature values, parallel_tool_calls defaulting, async scheduling with prompt embeds on multimodal models, and the Gemma4 parsers. Note: the XverseForCausalLM model was removed upstream. Full changes: https://github.com/vllm-project/vllm/compare/b8336c3...6607a80`,
    es_ES: `Avanza la compilación nightly de vLLM incluida al commit 6607a80 (sigue en la línea upstream 0.23.1rc0). Novedades: soporte para los modelos MiniMax M3 y un cargador de vídeo Qwen3-VL, una corrección de seguridad que aplica el límite de tamaño de subida de audio antes de materializar el archivo completo, recuento de tokens multimodales en usage.prompt_tokens_details, y correcciones para valores de temperatura fuera de rango, el valor por defecto de parallel_tool_calls, la planificación asíncrona con prompt embeds en modelos multimodales y los parsers de Gemma4. Nota: el modelo XverseForCausalLM se eliminó en upstream. Cambios completos: https://github.com/vllm-project/vllm/compare/b8336c3...6607a80`,
    de_DE: `Aktualisiert den gebündelten vLLM-Nightly-Build auf Commit 6607a80 (weiterhin auf der Upstream-Linie 0.23.1rc0). Highlights: neue Modellunterstützung für MiniMax M3 und ein Qwen3-VL-Video-Loader, ein Sicherheitsfix, der das Größenlimit für Audio-Uploads vor dem vollständigen Materialisieren der Datei erzwingt, multimodale Token-Zählung in usage.prompt_tokens_details sowie Fehlerbehebungen für Temperaturwerte außerhalb des gültigen Bereichs, den Standardwert von parallel_tool_calls, asynchrones Scheduling mit Prompt-Embeds bei multimodalen Modellen und die Gemma4-Parser. Hinweis: Das Modell XverseForCausalLM wurde upstream entfernt. Vollständige Änderungen: https://github.com/vllm-project/vllm/compare/b8336c3...6607a80`,
    pl_PL: `Aktualizuje dołączoną kompilację nightly vLLM do commitu 6607a80 (nadal na upstreamowej linii 0.23.1rc0). Najważniejsze: obsługa modeli MiniMax M3 oraz loader wideo Qwen3-VL, poprawka bezpieczeństwa wymuszająca limit rozmiaru przesyłanego audio przed pełnym zmaterializowaniem pliku, liczba tokenów multimodalnych w usage.prompt_tokens_details, a także poprawki dla wartości temperatury spoza zakresu, domyślnej wartości parallel_tool_calls, asynchronicznego harmonogramowania z prompt embeds w modelach multimodalnych oraz parserów Gemma4. Uwaga: model XverseForCausalLM został usunięty w upstream. Pełne zmiany: https://github.com/vllm-project/vllm/compare/b8336c3...6607a80`,
    fr_FR: `Met à jour la version nightly de vLLM incluse vers le commit 6607a80 (toujours sur la ligne upstream 0.23.1rc0). Points forts : prise en charge des modèles MiniMax M3 et d'un chargeur vidéo Qwen3-VL, un correctif de sécurité appliquant la limite de taille des envois audio avant la matérialisation complète du fichier, le décompte des tokens multimodaux dans usage.prompt_tokens_details, ainsi que des corrections pour les valeurs de température hors plage, la valeur par défaut de parallel_tool_calls, la planification asynchrone avec prompt embeds sur les modèles multimodaux et les parseurs Gemma4. Remarque : le modèle XverseForCausalLM a été supprimé en amont. Changements complets : https://github.com/vllm-project/vllm/compare/b8336c3...6607a80`,
  },
  migrations: {
    up: async ({ effects }) => {},
    down: async ({ effects }) => {},
  },
})
