import { VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '0.23.1-rc.0:8',
  releaseNotes: {
    en_US: `Advances the bundled vLLM nightly build to commit 3f5a1e1 (still on the upstream 0.23.1rc0 line). Highlights: the Rust frontend gains a unified/combined parser interface, xgrammar structural-tag support for strict and required tool calling, echo for token-ID completion prompts, and corrected reasoning-parser semantics; new MiniMax-M3 pipeline-parallelism and OpenMOSS-Team model support, plus CPU chunked prefill and prefix caching for Qwen3.5 and AArch64 MoE acceleration; and bugfixes for MiniMax/Kimi K2 tool-call streaming, non-ASCII tool-call arguments, and a security fix for an infinite loop on NaN audio samples. The legacy BaiChuan/Baichuan models were removed. Full changes: https://github.com/vllm-project/vllm/compare/04c2a8d...3f5a1e1`,
    es_ES: `Avanza la compilación nightly de vLLM incluida al commit 3f5a1e1 (sigue en la línea upstream 0.23.1rc0). Destacados: el frontend Rust gana una interfaz de analizador unificada/combinada, soporte de structural-tag de xgrammar para llamadas a herramientas strict y required, echo para prompts de completions por ID de token y semántica de reasoning-parser corregida; nuevo soporte de paralelismo de pipeline para MiniMax-M3 y de modelos OpenMOSS-Team, además de prefill por fragmentos y caché de prefijos en CPU para Qwen3.5 y aceleración de MoE en AArch64; y correcciones para el streaming de llamadas a herramientas de MiniMax/Kimi K2, argumentos de llamadas a herramientas no ASCII y una corrección de seguridad para un bucle infinito con muestras de audio NaN. Se eliminaron los modelos heredados BaiChuan/Baichuan. Cambios completos: https://github.com/vllm-project/vllm/compare/04c2a8d...3f5a1e1`,
    de_DE: `Aktualisiert den gebündelten vLLM-Nightly-Build auf Commit 3f5a1e1 (weiterhin auf der Upstream-Linie 0.23.1rc0). Highlights: Das Rust-Frontend erhält eine vereinheitlichte/kombinierte Parser-Schnittstelle, xgrammar-Structural-Tag-Unterstützung für strict- und required-Tool-Calls, echo für Token-ID-Completion-Prompts sowie korrigierte Reasoning-Parser-Semantik; neue Pipeline-Parallelism-Unterstützung für MiniMax-M3 und OpenMOSS-Team-Modelle, dazu Chunked-Prefill und Prefix-Caching auf CPU für Qwen3.5 sowie AArch64-MoE-Beschleunigung; und Fehlerbehebungen für MiniMax-/Kimi-K2-Tool-Call-Streaming, Nicht-ASCII-Tool-Call-Argumente und ein Sicherheitsfix für eine Endlosschleife bei NaN-Audio-Samples. Die veralteten BaiChuan/Baichuan-Modelle wurden entfernt. Vollständige Änderungen: https://github.com/vllm-project/vllm/compare/04c2a8d...3f5a1e1`,
    pl_PL: `Aktualizuje dołączoną kompilację nightly vLLM do commitu 3f5a1e1 (nadal na upstreamowej linii 0.23.1rc0). Najważniejsze: frontend Rust zyskuje zunifikowany/łączony interfejs parsera, obsługę structural-tag z xgrammar dla wywołań narzędzi strict i required, echo dla promptów completions po ID tokena oraz poprawioną semantykę reasoning-parser; nowa obsługa równoległości potoku dla MiniMax-M3 i modeli OpenMOSS-Team, a także prefill fragmentowy i cache prefiksów na CPU dla Qwen3.5 oraz przyspieszenie MoE na AArch64; a także poprawki strumieniowania wywołań narzędzi MiniMax/Kimi K2, argumentów wywołań narzędzi spoza ASCII oraz poprawka bezpieczeństwa dla nieskończonej pętli przy próbkach audio NaN. Usunięto przestarzałe modele BaiChuan/Baichuan. Pełne zmiany: https://github.com/vllm-project/vllm/compare/04c2a8d...3f5a1e1`,
    fr_FR: `Met à jour la version nightly de vLLM incluse vers le commit 3f5a1e1 (toujours sur la ligne upstream 0.23.1rc0). Points forts : le frontend Rust gagne une interface de parseur unifiée/combinée, la prise en charge des structural-tag de xgrammar pour les appels d'outils strict et required, echo pour les prompts de completions par ID de token et une sémantique de reasoning-parser corrigée ; nouvelle prise en charge du parallélisme de pipeline pour MiniMax-M3 et des modèles OpenMOSS-Team, ainsi que le prefill par blocs et la mise en cache de préfixes sur CPU pour Qwen3.5 et l'accélération MoE sur AArch64 ; et des corrections pour le streaming des appels d'outils MiniMax/Kimi K2, les arguments d'appels d'outils non ASCII et un correctif de sécurité pour une boucle infinie sur des échantillons audio NaN. Les modèles hérités BaiChuan/Baichuan ont été supprimés. Changements complets : https://github.com/vllm-project/vllm/compare/04c2a8d...3f5a1e1`,
  },
  migrations: {
    up: async ({ effects }) => {},
    down: async ({ effects }) => {},
  },
})
