import { VersionInfo } from '@start9labs/start-sdk'

export const current = VersionInfo.of({
  version: '0.23.1-rc.0:9',
  releaseNotes: {
    en_US: `Advances the bundled vLLM nightly build to commit 68ee830 (still on the upstream 0.23.1rc0 line). Highlights: new GLM-5/DSV3.2 model support, DiffusionGemma tensor parallelism, and Voxtral migrated to the mistral-common 1.11.5 audio API; the Rust frontend switches its TLS backend from rustls to native-tls/OpenSSL, migrates gemma4 to the unified parser, preserves tool-call event ordering, and now rejects min_tokens above max_tokens; the render endpoints gain token offsets and there is a new VLLM_GPU_SYNC_CHECK debug env var; bugfixes for relative allowed-local-media paths, an NVFP4+MTP crash, and a macOS/Apple Silicon CPU build hang (OpenMP now enabled). The legacy Grok and Aquila model architectures were removed. Full changes: https://github.com/vllm-project/vllm/compare/3f5a1e1...68ee830`,
    es_ES: `Avanza la compilación nightly de vLLM incluida al commit 68ee830 (sigue en la línea upstream 0.23.1rc0). Destacados: nuevo soporte de modelos GLM-5/DSV3.2, paralelismo de tensores para DiffusionGemma y Voxtral migrado a la API de audio mistral-common 1.11.5; el frontend Rust cambia su backend TLS de rustls a native-tls/OpenSSL, migra gemma4 al analizador unificado, conserva el orden de los eventos de llamadas a herramientas y ahora rechaza min_tokens mayor que max_tokens; los endpoints de render incorporan desplazamientos de tokens y hay una nueva variable de entorno de depuración VLLM_GPU_SYNC_CHECK; correcciones para rutas relativas de medios locales permitidos, un fallo de NVFP4+MTP y un bloqueo de la compilación de CPU en macOS/Apple Silicon (ahora con OpenMP habilitado). Se eliminaron las arquitecturas heredadas Grok y Aquila. Cambios completos: https://github.com/vllm-project/vllm/compare/3f5a1e1...68ee830`,
    de_DE: `Aktualisiert den gebündelten vLLM-Nightly-Build auf Commit 68ee830 (weiterhin auf der Upstream-Linie 0.23.1rc0). Highlights: neue Unterstützung für GLM-5/DSV3.2-Modelle, Tensor-Parallelismus für DiffusionGemma und Voxtral auf die mistral-common-1.11.5-Audio-API migriert; das Rust-Frontend wechselt sein TLS-Backend von rustls zu native-tls/OpenSSL, migriert gemma4 auf den vereinheitlichten Parser, bewahrt die Reihenfolge der Tool-Call-Events und lehnt nun min_tokens größer als max_tokens ab; die Render-Endpunkte erhalten Token-Offsets und es gibt eine neue Debug-Umgebungsvariable VLLM_GPU_SYNC_CHECK; Fehlerbehebungen für relative erlaubte lokale Medienpfade, einen NVFP4+MTP-Absturz und einen Hänger des CPU-Builds unter macOS/Apple Silicon (OpenMP jetzt aktiviert). Die veralteten Modellarchitekturen Grok und Aquila wurden entfernt. Vollständige Änderungen: https://github.com/vllm-project/vllm/compare/3f5a1e1...68ee830`,
    pl_PL: `Aktualizuje dołączoną kompilację nightly vLLM do commitu 68ee830 (nadal na upstreamowej linii 0.23.1rc0). Najważniejsze: nowa obsługa modeli GLM-5/DSV3.2, równoległość tensorów dla DiffusionGemma oraz Voxtral przeniesiony na API audio mistral-common 1.11.5; frontend Rust zmienia backend TLS z rustls na native-tls/OpenSSL, migruje gemma4 do zunifikowanego parsera, zachowuje kolejność zdarzeń wywołań narzędzi i odrzuca min_tokens większe niż max_tokens; endpointy render zyskują przesunięcia tokenów oraz pojawia się nowa zmienna środowiskowa debugowania VLLM_GPU_SYNC_CHECK; poprawki dla względnych dozwolonych ścieżek mediów lokalnych, awarii NVFP4+MTP oraz zawieszenia kompilacji CPU na macOS/Apple Silicon (włączono OpenMP). Usunięto przestarzałe architektury modeli Grok i Aquila. Pełne zmiany: https://github.com/vllm-project/vllm/compare/3f5a1e1...68ee830`,
    fr_FR: `Met à jour la version nightly de vLLM incluse vers le commit 68ee830 (toujours sur la ligne upstream 0.23.1rc0). Points forts : nouvelle prise en charge des modèles GLM-5/DSV3.2, parallélisme de tenseurs pour DiffusionGemma et Voxtral migré vers l'API audio mistral-common 1.11.5 ; le frontend Rust change son backend TLS de rustls vers native-tls/OpenSSL, migre gemma4 vers le parseur unifié, préserve l'ordre des événements d'appels d'outils et rejette désormais min_tokens supérieur à max_tokens ; les endpoints de rendu gagnent des décalages de tokens et une nouvelle variable d'environnement de débogage VLLM_GPU_SYNC_CHECK apparaît ; corrections pour les chemins relatifs de médias locaux autorisés, un plantage NVFP4+MTP et un blocage de la compilation CPU sur macOS/Apple Silicon (OpenMP désormais activé). Les architectures de modèles héritées Grok et Aquila ont été supprimées. Changements complets : https://github.com/vllm-project/vllm/compare/3f5a1e1...68ee830`,
  },
  migrations: {
    up: async ({ effects }) => {},
    down: async ({ effects }) => {},
  },
})
